import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import { GoogleTagManager } from '@next/third-parties/google'
import "./globals.css";

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GoogleTagManager gtmId="G-P6XTRVZP4H" />

      <body
        className={`${rubik.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
